### PR TITLE
Fabo/node compatibility

### PR DESCRIPTION
**Pull request by faboweb**
Removed `isomorphic-fetch` as it can be included in the wrapping application.

### CODE REVIEW

**Comment by faboweb** [comment]
@AlexBHarley  I needed to revert your changes as it made the lib not working in browsers. I added a simpler solution to the readme. Can you check if that works for you?

**Comment by AlexBHarley** [comment]
Flat out at the moment but will try take a look on Monday. We're maintaining a fork right now so feel free to merge as long as it works for you.

**Comment by faboweb** [comment]
This can wait until next week ;)

**Comment by faboweb** [comment]
Closing as no response ;)

**Pull request closed without merging**
